server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/recipehelper
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:15432/postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'false'